export const NewsImage = {
    peek_into_rating: require('../../assets/newsroom/peek-into-rating.jpg'),
    assets: require('../../assets/newsroom/assets.png'),
    info: require('../../assets/newsroom/info.png'),
    leaderboard: require('../../assets/newsroom/leaderboard.png'),
    relax: require('../../assets/newsroom/relax.jpg'),
    when_we_say_serch: require('../../assets/newsroom/when-we-say-serch.png'),
    service_providing_platform: require('../../assets/newsroom/service-providing-platform.jpg'),
    operating_system: require('../../assets/newsroom/operating-system.jpg'),
    privacy_setting: require('../../assets/newsroom/privacy-setting.jpg'),
    safety_behaviour: require('../../assets/newsroom/safety-behave.jpg'),
    two_way_rating: require('../../assets/newsroom/two-way-rating.jpg'),
    check_availability: require('../../assets/newsroom/check-availability.jpg'),
}

export const BlogsImage = {
    five_star_user: require('../../assets/blog/five-star-user.jpg'),
    provider_features_and_tips: require('../../assets/blog/provider-features-and-tips.jpg'),
    five_star_rating: require('../../assets/blog/five-star-rating.jpg'),
    on_service_trip: require('../../assets/blog/on-service-trip.jpg'),
    rate_like_a_pro: require('../../assets/blog/rate-like-a-pro.jpg'),
    safer_way: require('../../assets/blog/safer-way.jpg'),
    user_features_and_tips: require('../../assets/blog/user-features-and-tips.jpg'),
    tip2fix: require('../../assets/blog/tip2fix.jpg'),
    rsLink: require('../../assets/blog/rs-link.jpg'),
    requestSharing: require('../../assets/blog/requestSharing.jpg'),
    provideSharing: require('../../assets/blog/provideSharing.jpg'),
    business_or_individual: require('../../assets/blog/business-or-individual.jpg'),
    cheers_to_a_new_beginning: require('../../assets/blog/cheers-to-a-new-beginning.jpg'),
    introduction: require('../../assets/blog/introduction.jpg'),
    keep_moving: require('../../assets/blog/keep-moving.jpg'),
    movement: require('../../assets/blog/movement.jpg'),
    promo: require('../../assets/blog/promo.jpg'),
    promoCode: require('../../assets/blog/promo-code.jpg'),
    safety_tips: require('../../assets/blog/safety-tips.jpg'),
    sharing: require('../../assets/blog/sharing.jpg'),
    subscription: require('../../assets/blog/subscription.jpg'),
    we_are_here: require('../../assets/blog/we-are-here.jpg'),
    we_are_live: require('../../assets/blog/we-are-live.jpg'),
}